apiVersion: v1
kind: Service
metadata:
  name: audit
  labels:
    app: audit
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    nodePort: 30010
  selector:
    app: audit
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: audit
spec:
  selector:
    matchLabels:
      app: audit
  replicas: 1 
  template: 
    metadata:
      labels:
        app: audit
    spec:
      containers:
      - name: audit
        image: xap/audit:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: KidsXap__Mongo__ConnectionString
          value: "mongodb://mongo:27017" 
        - name: APP_SUBSCRIBERID
          value: "f48ec90a-0afe-4e01-ac06-2b93bbb19c5d"
        - name: SERVICEBUS_PUBLISHONLY
          value: "true"
      hostAliases:
      - ip: "10.10.10.111"
        hostnames:
          - "id.dev.kidsxap.com.au"
---
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: audit-consumer
spec:
  selector:
    matchLabels:
      app: audit-consumer
  replicas: 1
  template: 
    metadata:
      labels:
        app: audit-consumer
    spec:
      containers:
      - name: audit-consumer
        image: xap/audit/worker
        imagePullPolicy: IfNotPresent
        resources:
         requests:
          memory: "0.25Gi"
          cpu: "100m"
        env:
        - name: KidsXap__Mongo__ConnectionString 
          value: "mongodb://mongo:27017" 
        - name: APP_SUBSCRIBERID
          value: "f48ec90a-0afe-4e01-ac06-2b93bbb19c5d"
        - name: SERVICEBUS_PUBLISHONLY
          value: "false"
---