apiVersion: v1
kind: Service
metadata:
  name: emailtemplates
  labels:
    app: emailtemplates
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    nodePort: 30013
  selector:
    app: emailtemplates
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: emailtemplates
spec:
  selector:
    matchLabels:
      app: emailtemplates
  replicas: 1 
  template: 
    metadata:
      labels:
        app: emailtemplates
    spec:
      containers:
      - name: emailtemplates
        image: xap/emailtemplates:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: ENV_PREFIX
          value: KidsXap
        - name: APP_SUBSCRIBERID
          value: "f48ec90a-0afe-4e01-ac06-2b93bbb19c5d"
      hostAliases:
      - ip: "10.10.10.111"
        hostnames:
          - "id.dev.kidsxap.com.au"
---