apiVersion: v1
kind: Service
metadata:
  name: payments
  labels:
    app: payments
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    nodePort: 30015
  selector:
    app: payments
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: payments
spec:
  selector:
    matchLabels:
      app: payments
  replicas: 1 
  template: 
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - name: payments
        image: xap/payments:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: ENV_PREFIX
          value: KidsXap
        - name: APP_SUBSCRIBERID
          value: "f48ec90a-0afe-4e01-ac06-2b93bbb19c5d"
      hostAliases:
      - ip: "10.10.10.111"
        hostnames:
          - "id.dev.kidsxap.com.au"
---
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: payments-consumer
spec:
  selector:
    matchLabels:
      app: payments-consumer
  replicas: 1
  template: 
    metadata:
      labels:
        app: payments-consumer
    spec:
      containers:
      - name: payments-consumer
        image: xap/payments/worker
        imagePullPolicy: IfNotPresent
        resources:
         requests:
          memory: "0.25Gi"
          cpu: "100m"
        env:
        - name: ENV_PREFIX
          value: KidsXap
        - name: APP_SUBSCRIBERID
          value: "f48ec90a-0afe-4e01-ac06-2b93bbb19c5d"
        - name: PUSHGATEWAY_ENDPOINT
          value: "http://pushgateway-prometheus-pushgateway.monitoring.svc.cluster.local:9091/metrics"
        - name: SERVICEBUS_PUBLISHONLY
          value: "false"
---
