apiVersion: v1
kind: Service
metadata:
  name: subscriptions
  labels:
    app: subscriptions
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    nodePort: 30016
  selector:
    app: subscriptions
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: subscriptions
spec:
  selector:
    matchLabels:
      app: subscriptions
  replicas: 1 
  template: 
    metadata:
      labels:
        app: subscriptions
    spec:
      containers:
      - name: subscriptions
        image: xap/subscriptions
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: ENV_PREFIX
          value: KidsXap
        - name: APP_SUBSCRIBERID
          value: "f48ec90a-0afe-4e01-ac06-2b93bbb19c5d"
      hostAliases:
      - ip: "192.168.219.180"
        hostnames:
          - "id.dev.kidsxap.com.au"
---