apiVersion: v1
kind: Service
metadata:
  name: tags
  labels:
    app: tags
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    nodePort: 30012
  selector:
    app: tags
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: tags
spec:
  selector:
    matchLabels:
      app: tags
  replicas: 1 
  template: 
    metadata:
      labels:
        app: tags
    spec:
      containers:
      - name: tags
        image: xap/tags:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: ENV_PREFIX
          value: KidsXap
        - name: APP_SUBSCRIBERID
          value: "f48ec90a-0afe-4e01-ac06-2b93bbb19c5d"
      hostAliases:
      - ip: "192.168.0.9"
        hostnames:
          - "id.dev.kidsxap.com.au"
---
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: tags-consumer
spec:
  selector:
    matchLabels:
      app: tags-consumer
  replicas: 1
  template: 
    metadata:
      labels:
        app: tags-consumer
    spec:
      containers:
      - name: tags-consumer
        image: xap/tags/worker
        imagePullPolicy: IfNotPresent
        resources:
         requests:
          memory: "0.25Gi"
          cpu: "100m"
        env:
        - name: KidsXap__Mongo__ConnectionString 
          value: "mongodb://mongo:27017" 
        - name: APP_SUBSCRIBERID
          value: "f48ec90a-0afe-4e01-ac06-2b93bbb19c5d"
        - name: SERVICEBUS_PUBLISHONLY
          value: "false"
---