apiVersion: v1
kind: Service
metadata:
  name: userprofiles
  labels:
    app: userprofiles
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    nodePort: 30008
  selector:
    app: userprofiles
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: userprofiles
spec:
  selector:
    matchLabels:
      app: userprofiles
  replicas: 1 
  template: 
    metadata:
      labels:
        app: userprofiles
    spec:
      containers:
      - name: userprofiles
        image: xap/userprofiles
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: ENV_PREFIX
          value: KidsXap
        - name: APP_SUBSCRIBERID
          value: "f48ec90a-0afe-4e01-ac06-2b93bbb19c5d"
      hostAliases:
      - ip: "10.10.10.139"
        hostnames:
          - "localhost"
---