apiVersion: v1
kind: Service
metadata:
  name: waitlist
  labels:
    app: waitlist
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    nodePort: 30019
  selector:
    app: waitlist
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: waitlist
spec:
  selector:
    matchLabels:
      app: waitlist
  replicas: 1 
  template: 
    metadata:
      labels:
        app: waitlist
    spec:
      containers:
      - name: waitlist
        image: xap/waitlist/api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: APP_SUBSCRIBERID
          value: "f48ec90a-0afe-4e01-ac06-2b93bbb19c5d"        
      hostAliases:
      - ip: "10.10.10.139"
        hostnames:
          - "localhost"
---
---
apiVersion: v1
kind: Service
metadata:
  name: waitlist-lead
  labels:
    app: waitlist-lead
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    nodePort: 30023
  selector:
    app: waitlist-lead
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: waitlist-lead
spec:
  selector:
    matchLabels:
      app: waitlist-lead
  replicas: 1 
  template: 
    metadata:
      labels:
        app: waitlist-lead
    spec:
      containers:
      - name: waitlist-lead
        image: xap/waitlist-lead/api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: APP_SUBSCRIBERID
          value: "f48ec90a-0afe-4e01-ac06-2b93bbb19c5d"        
      hostAliases:
      - ip: "10.10.10.139"
        hostnames:
          - "localhost"
---
---
apiVersion: v1
kind: Service
metadata:
  name: waitlist-toursetup
  labels:
    app: waitlist-toursetup
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    nodePort: 30024
  selector:
    app: waitlist-toursetup
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: waitlist-toursetup
spec:
  selector:
    matchLabels:
      app: waitlist-toursetup
  replicas: 1 
  template: 
    metadata:
      labels:
        app: waitlist-toursetup
    spec:
      containers:
      - name: waitlist-toursetup
        image: xap/waitlist-toursetup/api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: APP_SUBSCRIBERID
          value: "f48ec90a-0afe-4e01-ac06-2b93bbb19c5d"        
      hostAliases:
      - ip: "10.10.10.139"
        hostnames:
          - "localhost"
---
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: waitlist-consumer
spec:
  selector:
    matchLabels:
      app: waitlist-consumer
  replicas: 1
  template: 
    metadata:
      labels:
        app: waitlist-consumer
    spec:
      containers:
      - name: waitlist-consumer
        image: xap/waitlist/worker
        imagePullPolicy: IfNotPresent
        resources:
         requests:
          memory: "0.25Gi"
          cpu: "100m"
        env:
        - name: ENV_PREFIX
          value: KidsXap
        - name: APP_SUBSCRIBERID
          value: "f48ec90a-0afe-4e01-ac06-2b93bbb19c5d"
        - name: PUSHGATEWAY_ENDPOINT
          value: "http://pushgateway-prometheus-pushgateway.monitoring.svc.cluster.local:9091/metrics"        
---
---
apiVersion: v1
kind: Service
metadata:
  name: waitlist-lead
  labels:
    app: waitlist-lead
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    nodePort: 30023
  selector:
    app: waitlist-lead
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: waitlist-lead
spec:
  selector:
    matchLabels:
      app: waitlist-lead
  replicas: 1 
  template: 
    metadata:
      labels:
        app: waitlist-lead
    spec:
      containers:
      - name: waitlist-lead
        image: xap/waitlist-lead/api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: APP_SUBSCRIBERID
          value: "f48ec90a-0afe-4e01-ac06-2b93bbb19c5d"        
      hostAliases:
      - ip: "10.10.10.139"
        hostnames:
          - "id.dev.kidsxap.com.au"
---
---
apiVersion: v1
kind: Service
metadata:
  name: waitlist-toursetup
  labels:
    app: waitlist-toursetup
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    nodePort: 30024
  selector:
    app: waitlist-toursetup
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: waitlist-toursetup
spec:
  selector:
    matchLabels:
      app: waitlist-toursetup
  replicas: 1 
  template: 
    metadata:
      labels:
        app: waitlist-toursetup
    spec:
      containers:
      - name: waitlist-toursetup
        image: xap/waitlist-toursetup/api:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: APP_SUBSCRIBERID
          value: "f48ec90a-0afe-4e01-ac06-2b93bbb19c5d"        
      hostAliases:
      - ip: "10.10.10.139"
        hostnames:
          - "id.dev.kidsxap.com.au"
---
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: waitlist-consumer
spec:
  selector:
    matchLabels:
      app: waitlist-consumer
  replicas: 1
  template: 
    metadata:
      labels:
        app: waitlist-consumer
    spec:
      containers:
      - name: waitlist-consumer
        image: xap/waitlist/worker
        imagePullPolicy: IfNotPresent
        resources:
         requests:
          memory: "0.25Gi"
          cpu: "100m"
        env:
        - name: ENV_PREFIX
          value: KidsXap
        - name: APP_SUBSCRIBERID
          value: "f48ec90a-0afe-4e01-ac06-2b93bbb19c5d"
        - name: PUSHGATEWAY_ENDPOINT
          value: "http://pushgateway-prometheus-pushgateway.monitoring.svc.cluster.local:9091/metrics"        
---